[project]
name = "sicp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "calysto-scheme>=1.4.8",
    "jupyter>=1.1.1",
]
